<? if($page == "inmuebles"){$_SESSION["gnr_pag"] = URI_PATH;}elseif($page != "login"){unset($_SESSION["gnr_pag"]);}?>
<!DOCTYPE html>
<html>
<head>
<title><?=$title;?></title>
<meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<!--<meta property="fb:admins" content='100001282887976'/>-->
<!--<link rel="image_src" href="<?=URL_PATH;?>img/logo_soc.jpg" id="image_src" />-->
<meta name="title" content="<?=$title;?>" />
<? if($description != ""){?><meta name="description" content="<?=$description;?>" /><? }; if($keywords != ""){?><meta name="keywords" content="<?=$keywords;?>" /><? }?>
<meta name="robots" content="index, follow" />
<meta name="googlebot" content="index, follow" />
<? if($pagedet == 1){?><link rel="image_src" href="<?=$nimg;?>" id="image_src" /><? }?>
<!--<link rel="alternate" type="application/rss+xml" title="Generaccion.com - PORTADA" href="<?=URL_PATH;?>noticia/rss/" />-->
<link type="text/css" href="<?=URL_PATH;?>assets/css/styles.css" rel="stylesheet" charset="utf-8" /><? if(count($styles) > 0){foreach($styles as $style){ ?><link type="text/css" href="<?=URL_PATH;?>assets/<?=$style;?>" rel="stylesheet" charset="utf-8" /><? }}?>
<script type="text/javascript">var iurl='<?=URL_PATH;?>';</script><script type="text/javascript" src="<?=URL_PATH;?>assets/js/jquery-1.8.2.min.js" charset="utf-8"></script><script type="text/javascript" src="<?=URL_PATH;?>assets/js/fjs.extras.js" charset="utf-8"></script><? if($pagedet == 1){?><script type="text/javascript" src="https://maps.google.com/maps/api/js?sensor=false"></script><? };if($page=="micuenta-crearpublicacion"||$page=="micuenta-editarpublicacion"){?>

<script type='text/javascript' src='http://maps.googleapis.com/maps/api/js?key=AIzaSyD4qvb7mZexJhkXsc0jBqyeNlrEKLQ2pPI&sensor=true&#038;ver=3.4.2'></script>

<? }if(count($scripts) > 0){foreach($scripts as $script){ ?><script type="text/javascript" src="<?=URL_PATH;?>assets/<?=$script;?>" charset="utf-8"></script><? }}; if($javascript != ""){?><script type="text/javascript" charset="utf-8"><?=$javascript;?></script><? }?><script type="text/javascript">var _gaq=_gaq||[];_gaq.push(['_setAccount', 'UA-36101259-1']);_gaq.push(['_setDomainName', 'midepa.pe']);_gaq.push(['_trackPageview']);(function(){var ga=document.createElement('script');ga.type='text/javascript'; ga.async=true;ga.src=('https:'==document.location.protocol?'https://ssl':'http://www')+'.google-analytics.com/ga.js';var s=document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);})();</script><script language="javascript" type="text/javascript" src="<?=URL_PATH;?>/assets/js/js.js"></script><script type="text/javascript" src="<?=URL_PATH;?>assets/js/swfobject/swfobject.js" charset="utf-8"></script>
</head>
<body>
<div id="fb-root"></div>
<script>(function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(d.getElementById(id)) return;js=d.createElement(s);js.id=id;js.src="//connect.facebook.net/es_ES/all.js#xfbml=1";fjs.parentNode.insertBefore(js,fjs);}(document,'script','facebook-jssdk'));</script>
<div id="superior"><div class="sup"><div class="ins"><div class="flef"><span class="rss"><a href="<?=URL_PATH;?>rss/" target="_blank">RSS</a></span><span class="gnr"><a href="http://www.generaccion.com/usuarios/" target="_blank">2urpi</a></span><span class="fbk"><a href="https://www.facebook.com/pages/Midepape/125879437565772" target="_blank">Facebook</a></span><span class="twt"><a href="https://twitter.com/MiDepape" target="_blank">Twitter</a></span><span class="gog"><a href="https://plus.google.com/u/0/104823439872423969978/" target="_blank">Google+</a></span></div><? if($log != ""){?><div class="frig"><a href="<?=URL_PATH;?>micuenta/"><?=$lusn;?> (mi cuenta)</a> | <a href="<?=URL_PATH;?>cerrar-sesion/">Cerrar sesi&oacute;n</a></div><? }else{?><div class="ini"><span><a href="<?=URL_PATH;?>login/">Iniciar sesi&oacute;n</a></span><a href="<?=URL_PATH;?>registro/">Reg&iacute;strate</a></div><? }?></div></div>
  <div class="cab"><div class="log"><a href="<?=URL_PATH;?>"></a></div><div class="frig"><form method="get" action="<?=URL_PATH;?>search.php" id="cse-search-box"><div class="but"><input type="text" autocomplete="off" name="q" id="q" class="txt" style="width:270px;" /></div><div class="btn btx"><span><input type="submit" name="sa" id="btnbus" value="Buscar" /><input type="hidden" value="005112579141928768649:sbzfdghrr6u" name="cx"><input type="hidden" name="cof" value="FORID:11" /><input type="hidden" name="oe" value="UTF-8"></span></div></form><script type="text/javascript" src="http://www.google.com/coop/cse/brand?form=cse-search-box&lang=es"></script></div></div>
  <div class="nav"><ul class="ins"><div class="gra"></div><li<? if($page=="inicio"){echo ' class="sel"';}?>><a href="<?=URL_PATH;?>" class="hme">INICIO</a></li><li<? if($page=="inmuebles"){echo ' class="sel"';}?>><a href="<?=URL_PATH;?>inmuebles/">INMUEBLES</a></li><li<? if($page=="proyectos"){echo ' class="sel"';}?>><a href="<?=URL_PATH;?>proyectos/">PROYECTOS</a></li><li<? if($page=="constructoras"){echo ' class="sel"';}?>><a href="<?=URL_PATH;?>constructoras/">CONSTRUCTORAS</a></li><li<? if($page=="agentes-inmobiliarios"){echo ' class="sel"';}?>><a href="<?=URL_PATH;?>agentes-inmobiliarios/">AGENTES INMOBILIARIOS</a></li><li<? if($page=="publicar"){echo ' class="sel"';}?>><a href="<?=URL_PATH;?>registro/">PUBLICAR ANUNCIO</a></li><? if($log!=""){?><li class="car"><span></span><a href="<?=URL_PATH;?>pago-publicaciones.php">CARRITO</a></li><? }?></ul></div></div>
<div id="contenedor" class="ins">